# Generated by Django 4.1.1 on 2022-10-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_alter_appointment_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tests',
            field=models.ManyToManyField(blank=True, null=True, to='appointment.test'),
        ),
    ]
