# Generated by Django 4.1.1 on 2022-10-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_alter_appointment_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='branch',
        ),
    ]
